--PROBLEM 1
select CASE_NUMBER, PRIMARY_TYPE, COMMUNITY_AREA_NAME
from ChicagoCrimeData as Cr
inner join ChicagoCensusData as Ce
on Ce.COMMUNITY_AREA_NUMBER=Cr.COMMUNITY_AREA_NUMBER
Where Ce.COMMUNITY_AREA_NUMBER=18

--PROBLEM 2
Select CASE_NUMBER, PRIMARY_TYPE,COMMUNITY_AREA_NAME
From ChicagoCrimeData as Cr
right join ChicagoCensusData as Ce
on Ce.COMMUNITY_AREA_NUMBER=Cr.COMMUNITY_AREA_NUMBER
where Cr.LOCATION_DESCRIPTION Like '%SCHOOL%'

--PROBLEM 3
select Ce.COMMUNITY_AREA_NUMBER, CASE_NUMBER
from ChicagoCrimeData as Cr
full outer join ChicagoCensusData as Ce
on Ce.COMMUNITY_AREA_NUMBER=Cr.COMMUNITY_AREA_NUMBER
where ce.COMMUNITY_AREA_NUMBER in (36, 34, 77, NULL)